// Queue model and pure helpers for BG Remover batch runs.
//
// Deliberately React-free: app/bg-remover/page.tsx owns the state machine, this module owns the
// shapes, the naming rules and the canvas/PNG plumbing that both the page and the queue rows
// need. Nothing here holds state — the only mutable thing in the feature is the page's items[].

import { detectImageColumns, detectTitleColumn, parseCSV } from '@/lib/csv';

import type { LoadProgress } from './engine';
import { TRANSPARENT, type SubjectBounds } from './safe-area';
import { isHeicFile } from './heic';
import type { RegionReport } from './regions';

export type BgItemStatus =
  | 'ready'
  | 'loading-model'
  | 'removing'
  /** Being regenerated by Azure GPT-Image; the result replaces the item's source image. */
  | 'editing'
  | 'done'
  | 'error'
  | 'cancelled';

export type BgItemSource =
  // `regenerated` marks a file the AI edit produced (paid Azure output). Autosave uses it to
  // decide which file sources are worth persisting — ordinary dropped originals are not.
  | { kind: 'file'; file: File; regenerated?: boolean }
  | { kind: 'url'; url: string }
  // Restored from a saved project: the cutout exists but the original bytes were never saved,
  // so there is nothing to re-run inference on. `label` is the provenance shown in the UI.
  | { kind: 'archived'; label: string };

/** Whether "remove background again" is possible — archived items have no original to re-run. */
export function canRetry(item: BgItem): boolean {
  return item.source.kind !== 'archived';
}

/**
 * Whether two sources point at the same image. Deliberately not `===`: in a live session the
 * item's original import and its current source are literally the same object, but a project or
 * autosave restore rebuilds each half separately — two `new File([slice], name)` values, two
 * copies of the same URL string — so reference equality reports "these differ" for every
 * restored row and the compare dialog offers a duplicate pane on all of them. Files are matched
 * on name+size+type rather than on the object; lastModified is left out on purpose because a
 * reconstructed File stamps it with the moment it was rebuilt, not the moment it was imported.
 */
export function sameSource(a: BgItemSource | undefined, b: BgItemSource | undefined): boolean {
  if (a === b) return true;
  if (!a || !b) return false;
  if (a.kind === 'url' && b.kind === 'url') return a.url === b.url;
  if (a.kind === 'file' && b.kind === 'file') {
    const x = a.file;
    const y = b.file;
    return x === y || (x.name === y.name && x.size === y.size && x.type === y.type);
  }
  if (a.kind === 'archived' && b.kind === 'archived') return a.label === b.label;
  return false;
}

/**
 * The as-imported source, but only while it still shows something the current source does not —
 * i.e. the item has actually been through an AI edit. Everything that offers "see the original"
 * asks through here so an untouched (or restored, see sameSource) row is not given a second pane
 * of the same picture.
 */
export function importedSource(item: BgItem): BgItemSource | null {
  const first = item.originalSource;
  if (!first || sameSource(first, item.source)) return null;
  return first;
}

/**
 * Which CSV cell an item was imported from. Kept on the ITEM rather than inside its source:
 * an AI edit replaces the source with the regenerated file, and a row that has been through
 * Azure must still answer "which CSV row are you?" — otherwise remapping the name column
 * cannot reach it, and remapping the image columns mints a duplicate for a row already queued.
 */
export interface CsvOrigin {
  /** Record index, header row excluded — the row number draftsFromCsv iterated. */
  row: number;
  /** Header of the image column the URL was read out of. */
  column: string;
}

/** Map key for a CSV cell. The row is numeric, so the first space splits it unambiguously. */
export function csvCellKey(origin: CsvOrigin): string {
  return `${origin.row} ${origin.column}`;
}

export function sameCsvOrigin(a: CsvOrigin | undefined, b: CsvOrigin | undefined): boolean {
  if (!a || !b) return a === b;
  return a.row === b.row && a.column === b.column;
}

/**
 * The CSV image an item stands for, whatever its source has since become. An AI edit swaps
 * `source` for the generated file, so the URL that identifies the row survives only in
 * `originalSource` — without looking there, a row that has been through Azure cannot be
 * recognised as the row it came from.
 *
 * A cell is NOT an identity on its own: `{row, column}` is a position, and every CSV exported
 * from the same template has the same positions. Row 0 of a second file matched row 0 of the
 * first, so re-dropping a corrected sheet reused the stale item wholesale — the fixed URL was
 * never fetched and the export shipped the old picture under the new title. Anything that
 * decides "this queued row IS that CSV row" has to agree on the picture too, which is also what
 * makes an inserted row (every later position shifts by one) fall through to the URL match
 * instead of cross-assigning the whole tail.
 */
export function csvSourceUrl(item: BgItem): string | null {
  if (item.source.kind === 'url') return item.source.url;
  const first = item.originalSource;
  return first && first.kind === 'url' ? first.url : null;
}

/**
 * A finished cutout, stored compressed. Holding a full-resolution canvas per item is what
 * exhausted memory on real batches: a 3000px photo is 36 MB as RGBA and under 2 MB as lossless
 * WebP. The preview is everything the UI draws; the blob is decoded on demand at export.
 */
export interface BgCutout {
  /** Full-resolution (post-cap) lossless WebP master. */
  blob: Blob;
  /** Subject bbox in FULL-resolution pixels. */
  bounds: SubjectBounds | null;
  width: number;
  height: number;
  /** Faint out-of-bbox pixel share from lib/bg/regions.measureFaintResidue — quality signal.
   *  Absent on restored projects/autosaves (not persisted; only fresh runs measure it). */
  residueFraction?: number;
}

export interface BgItem {
  id: number;
  /** Export filename stem, pre-sanitising. From the CSV title column or the file name. */
  name: string;
  source: BgItemSource;
  /**
   * Decoded input, populated lazily on first run. Released as soon as a cutout exists — the
   * before/after view re-decodes from `source`, which costs one read instead of a permanent
   * full-resolution bitmap per queued image.
   */
  original: HTMLImageElement | null;
  cutout: BgCutout | null;
  status: BgItemStatus;
  error?: string;
  durationMs?: number;
  /** Graphic regions the product-only filter dropped, so a heuristic stays auditable. */
  removedRegions?: number;
  /** Per-region measurements, shown in the compare dialog so decisions can be inspected. */
  regionReport?: RegionReport[];
  /**
   * Per-item tile-fit override, set from the selection bar. undefined follows the global
   * toggle; true/false pin this image regardless of it. Everything that renders or exports a
   * tile must go through the page's effectiveTileFit(), never read the global directly.
   */
  tileFit?: boolean;
  /**
   * One-slot undo: what the last Redo / AI edit replaced. AI edit swaps the SOURCE too (the
   * regenerated file becomes the new input), so undo must restore both halves together.
   * Overwritten by the next redo, cleared by undo itself.
   */
  prev?: { source: BgItemSource; cutout: BgCutout | null };
  /**
   * The source this item was FIRST imported with, captured once and immutable from then on.
   * Reference only — nothing runs inference on it, and it is deliberately not part of the undo
   * slot above: `prev` holds one step, so the second AI edit overwrote the pre-edit input and
   * Undo cleared what was left, after which nothing in the item still pointed at the CSV image.
   * That is what made the compare dialog show the AI output on both sides and dropped the
   * copy/open-URL buttons off an edited row.
   *
   * The page writes it at the moment of the first source replacement, guarded so a later edit
   * cannot move it (`originalSource: item.originalSource ?? item.source`), and undo must leave
   * it alone. No release hook: it carries a File or a URL string, never an object URL, so
   * releaseItem() has nothing to free here.
   */
  originalSource?: BgItemSource;
  /**
   * Which group of the queue this item belongs to. Nothing sets or reads it yet — it exists so
   * the batching phase can land without another pass over every shape that carries a BgItem;
   * absent means the single implicit batch that every item is in today.
   */
  batch?: number;
  /** Set for items imported from a CSV; absent for dropped files and pasted images. */
  csv?: CsvOrigin;
}

/** preview px per full-resolution px, for mapping bounds onto a decoded preview. */
export function previewScale(cutout: BgCutout, preview: ImageBitmap): number {
  return cutout.width ? preview.width / cutout.width : 1;
}

/** Full-resolution pixels for export. Caller owns the bitmap and must close() it. */
export function decodeCutout(cutout: BgCutout): Promise<ImageBitmap> {
  return createImageBitmap(cutout.blob);
}

/** What an input path emits. Ids are assigned when the page appends the drafts. */
export interface BgItemDraft {
  name: string;
  source: BgItemSource;
  csv?: CsvOrigin;
}

// Ids must survive removals, so they count up from the highest live id rather than the length.
export function nextItemId(items: BgItem[]): number {
  return items.reduce((max, item) => (item.id > max ? item.id : max), -1) + 1;
}

export function createItems(drafts: BgItemDraft[], startId: number): BgItem[] {
  return drafts.map((draft, i) => ({
    id: startId + i,
    name: draft.name,
    source: draft.source,
    original: null,
    cutout: null,
    status: 'ready',
    ...(draft.csv ? { csv: draft.csv } : null),
  }));
}

// ---- Naming ---------------------------------------------------------------

const EXTENSION_RE = /\.[a-z0-9]{1,5}$/i;
const HTTP_URL_RE = /^https?:\/\//i;

export function stripExtension(fileName: string): string {
  return fileName.replace(EXTENSION_RE, '');
}

/** Last path segment of an image URL, minus query and extension. '' when unusable. */
export function nameFromUrl(url: string): string {
  try {
    // The base only matters for relative inputs, which should not occur here; it keeps the
    // parse from throwing on one so a single odd cell cannot kill a whole CSV import.
    const { pathname } = new URL(url, 'https://invalid.example');
    const segment = pathname.split('/').filter(Boolean).pop() ?? '';
    return stripExtension(decodeURIComponent(segment));
  } catch {
    return '';
  }
}

/** Same rules as the compositor's export naming, so both products name files identically. */
export function sanitizeName(raw: string, fallback: string): string {
  const base = (raw || '')
    .replace(/[^\w\- ]+/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase();
  return base || fallback;
}

export interface ExportNameOptions {
  /**
   * Prefix each name with its zero-padded position. On by default because one CSV row can
   * produce several images that share a title — without the prefix they would collide inside
   * the ZIP and only the last would survive. Turn it off when names are already unique.
   */
  numbered?: boolean;
  extension?: string;
}

export function exportFileName(
  name: string,
  index: number,
  options: ExportNameOptions = {},
): string {
  const { numbered = true, extension = 'png' } = options;
  const position = index + 1;
  const base = sanitizeName(name, `image-${position}`);
  return numbered ? `${String(position).padStart(2, '0')}-${base}.${extension}` : `${base}.${extension}`;
}

/**
 * Names a whole export set. Without numbering, duplicate names would silently overwrite each
 * other inside the ZIP, so repeats get a -2, -3 … suffix; unique names stay untouched.
 */
export function exportFileNames(
  names: string[],
  options: ExportNameOptions = {},
): string[] {
  const used = new Map<string, number>();
  return names.map((name, index) => {
    const candidate = exportFileName(name, index, options);
    if (options.numbered === false) {
      const seen = used.get(candidate) ?? 0;
      used.set(candidate, seen + 1);
      if (seen > 0) {
        const dot = candidate.lastIndexOf('.');
        return `${candidate.slice(0, dot)}-${seen + 1}${candidate.slice(dot)}`;
      }
    }
    return candidate;
  });
}

// ---- Input paths ----------------------------------------------------------

export function isImageFile(file: File): boolean {
  // The extension fallback is for HEIC: some platforms hand those over with an empty MIME type.
  return file.type.startsWith('image/') || isHeicFile(file);
}

export function isCsvFile(file: File): boolean {
  return file.type === 'text/csv' || /\.csv$/i.test(file.name);
}

export function draftsFromFiles(files: File[]): BgItemDraft[] {
  return files.filter(isImageFile).map((file) => ({
    name: stripExtension(file.name),
    source: { kind: 'file', file },
  }));
}

export interface CsvImport {
  drafts: BgItemDraft[];
  /** The columns actually used (the auto-detected ones unless overridden). */
  imageColumns: string[];
  titleColumn: string;
  headers: string[];
  rowCount: number;
}

export interface CsvColumnOverrides {
  /** Column whose value names each image; '' or null = derive from the URL's filename. */
  nameColumn?: string | null;
  imageColumns?: string[];
}

/**
 * Flattens a compositor-shaped CSV: every http(s) URL in every image column becomes its own
 * queue item, named from the name column. Columns are auto-detected unless overridden — the
 * page re-runs this with overrides when the user remaps them. A row with three image columns
 * yields three items that share a name; the zero-padded export prefix keeps filenames distinct.
 */
export function draftsFromCsv(text: string, overrides: CsvColumnOverrides = {}): CsvImport {
  const { headers, records } = parseCSV(text);
  const imageColumns = overrides.imageColumns ?? detectImageColumns(headers, records);
  const titleColumn =
    overrides.nameColumn !== undefined
      ? overrides.nameColumn || ''
      : detectTitleColumn(headers, imageColumns);
  const drafts: BgItemDraft[] = [];
  records.forEach((record, row) => {
    const title = titleColumn ? record[titleColumn] : '';
    for (const column of imageColumns) {
      const url = record[column];
      if (!HTTP_URL_RE.test(url || '')) continue;
      drafts.push({
        name: title || nameFromUrl(url) || `row-${row + 1}`,
        source: { kind: 'url', url },
        csv: { row, column },
      });
    }
  });
  return { drafts, imageColumns, titleColumn, headers, rowCount: records.length };
}

// ---- Images and PNG bytes -------------------------------------------------

export function loadImageFromFile(file: File): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    // The object URL is intentionally NOT revoked on success: item.original keeps this element
    // alive for the before/after view, and revoking would blank it. releaseItem() frees it.
    img.onload = () => resolve(img);
    img.onerror = () => {
      URL.revokeObjectURL(img.src);
      reject(new Error(`Could not decode ${file.name}`));
    };
    img.src = URL.createObjectURL(file);
  });
}

/**
 * Releases the decoded original's object URL. Safe to call as soon as a cutout exists — the
 * compare view re-decodes from `source`. Returns nothing; the caller clears item.original.
 */
export function releaseOriginal(item: BgItem): void {
  const src = item.original?.src;
  if (src?.startsWith('blob:')) URL.revokeObjectURL(src);
}

/**
 * Frees everything an item holds. Call when dropping it from the queue, or on unmount.
 * Decoded previews are owned by lib/bg/preview-store.ts, not by the item — callers drop those
 * separately via dropPreview(id), which is why nothing here closes a bitmap.
 */
export function releaseItem(item: BgItem): void {
  releaseOriginal(item);
}

export function canvasToPngBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((b) => (b ? resolve(b) : reject(new Error('PNG encoding failed'))), 'image/png');
  });
}

export async function canvasToPngBytes(canvas: HTMLCanvasElement): Promise<Uint8Array> {
  return new Uint8Array(await (await canvasToPngBlob(canvas)).arrayBuffer());
}

/** Draws a decoded cutout onto a canvas, over a solid colour when one is set. */
export function flattenOnBackground(
  source: CanvasImageSource & { width: number; height: number },
  background: string,
): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = source.width;
  canvas.height = source.height;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('2D canvas context unavailable');
  if (background && background !== TRANSPARENT) {
    ctx.fillStyle = background;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
  }
  ctx.drawImage(source, 0, 0);
  return canvas;
}

/** Frees a canvas's backing store immediately rather than waiting for GC. */
export function releaseCanvas(canvas: HTMLCanvasElement): void {
  canvas.width = 0;
  canvas.height = 0;
}

export function downloadBlob(blob: Blob, fileName: string): void {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = fileName;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 5000);
}

// ---- "Save As" downloads ------------------------------------------------
// Chrome's save dialog (showSaveFilePicker) lets the file be named before it lands. The dialog
// only opens while the triggering click still counts as user activation, and a big ZIP export
// spends minutes encoding — so exports ask FIRST and write into the chosen destination when
// the bytes are ready, instead of picking at download time.

interface SaveHandle {
  createWritable(): Promise<{ write(data: Blob): Promise<void>; close(): Promise<void> }>;
}

interface SavePickerOptions {
  suggestedName?: string;
  types?: { description: string; accept: Record<string, string[]> }[];
}

/** The user's chosen destination, or how to proceed without one. */
export type SaveDestination = SaveHandle | 'fallback' | 'cancelled';

export async function pickSave(suggestedName: string): Promise<SaveDestination> {
  const picker = (
    window as { showSaveFilePicker?: (opts: SavePickerOptions) => Promise<SaveHandle> }
  ).showSaveFilePicker;
  // No picker (non-Chromium): the plain anchor download still applies the suggested name.
  if (typeof picker !== 'function') return 'fallback';
  try {
    // The types entry is what makes Chrome KEEP the extension when the user edits the name
    // in the dialog. Without it, typing "Continue" over "batch.zesku" saves an extensionless
    // file the dropzone then refuses — a real 3.3 GB support case.
    const ext = suggestedName.includes('.')
      ? suggestedName.slice(suggestedName.lastIndexOf('.')).toLowerCase()
      : '';
    const types = /^\.[a-z0-9]+$/.test(ext)
      ? [{ description: `${ext.slice(1).toUpperCase()} file`, accept: { 'application/octet-stream': [ext] } }]
      : undefined;
    return await picker.call(window, { suggestedName, ...(types ? { types } : null) });
  } catch (e) {
    // Dismissing the dialog means "don't export", not "export to the default name".
    if (e instanceof DOMException && e.name === 'AbortError') return 'cancelled';
    return 'fallback';
  }
}

/** Writes the finished bytes to a pickSave destination. False = the user had cancelled. */
export async function saveTo(dest: SaveDestination, blob: Blob, fileName: string): Promise<boolean> {
  if (dest === 'cancelled') return false;
  if (dest === 'fallback') {
    downloadBlob(blob, fileName);
    return true;
  }
  const writable = await dest.createWritable();
  await writable.write(blob);
  await writable.close();
  return true;
}

// ---- Run bookkeeping ------------------------------------------------------

export function needsCutout(item: BgItem): boolean {
  return item.cutout === null;
}

/** A BgItem already known to carry a cutout, so export paths need no null checks. */
export type CutoutItem = BgItem & { cutout: BgCutout };

export function withCutout(items: BgItem[]): CutoutItem[] {
  return items.filter((item): item is CutoutItem => item.cutout !== null);
}

/**
 * Runs `fn` over every item with at most `limit` in flight, preserving input order in the
 * result. Lanes pull the next index as they free up, so one slow item cannot stall the rest.
 */
export async function mapWithLimit<T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let next = 0;
  const lane = async () => {
    for (;;) {
      const index = next++;
      if (index >= items.length) return;
      results[index] = await fn(items[index], index);
    }
  };
  const lanes = Math.max(1, Math.min(limit, items.length));
  await Promise.all(Array.from({ length: lanes }, lane));
  return results;
}

export function isAbortError(error: unknown): boolean {
  return (error as { name?: string } | null)?.name === 'AbortError';
}

export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export const SETUP_HINT =
  'The model weights may be missing. Run `pnpm setup:bg`, then reload this page.';

/**
 * Whether a failure reads like a missing/unreachable weights file rather than a real inference
 * error. Only decides whether to ALSO show the setup hint — the original message is never
 * replaced, because "404" from a proxy and "404" from /models mean very different things.
 */
export function looksLikeMissingWeights(message: string): boolean {
  return /\b(fetch|404|network|not found|failed to load|unexpected token)\b/i.test(message);
}

// TinyPNG keys are a single alphanumeric token. Extracting it means hidden junk pasted from the
// dashboard (a trailing "Copied!") cannot silently invalidate the credentials. Same rule as the
// compositor's export, so one stored key works across both products.
export function extractTinifyKey(raw: string): string {
  const trimmed = raw.trim();
  return trimmed.match(/[A-Za-z0-9]{25,45}/)?.[0] ?? trimmed;
}

// ---- Formatting -----------------------------------------------------------

export function formatDuration(ms: number): string {
  return ms < 1000 ? `${Math.round(ms)} ms` : `${(ms / 1000).toFixed(1)} s`;
}

export function formatKb(bytes: number): string {
  return `${(bytes / 1024).toFixed(1)} KB`;
}

/** "Loading RMBG-1.4: 42 / 168 MB" — the line that proves the app is not frozen. */
export function describeDownload(progress: LoadProgress): string {
  return `Loading ${progress.label}: ${progress.loadedMb.toFixed(0)} / ${progress.totalMb.toFixed(0)} MB`;
}
